### ISSUE TITLE
build release error 

### ISSUE THREAD

**Issue by mahmoud-araby** [Kommunicate-io/Kommunicate-Flutter-Plugin#17]
I have an issue with the package when run in release mode the plugin does not log in with the user or the visitor session 
the package work perfectly in debug mode but not in the release mode
and I tried to view the prints it seems that all data is parsed as null in release mode but in debug mode all work fine
please check this error 

------------------------------------------- Release mode -----------------------------------------------------------
E/flutter (19683): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(Error, throw with null exception, null, null)
E/flutter (19683): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
E/flutter (19683): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
E/flutter (19683): <asynchronous suspension>
E/flutter (19683): #2      KommunicateFlutterPlugin.loginAsVisitor (package:kommunicate_flutter_plugin/kommunicate_flutter_plugin.dart:35)
E/flutter (19683): <asynchronous suspension>
E/flutter (19683): #3      _MainBoardState.liveChatCard.<anonymous closure> (package:scope_interior/pages/action_board.dart:329)
E/flutter (19683): <asynchronous suspension>
E/flutter (19683): 

------------------------------------ debug mode -------------------------------------------------------------

I/HttpRequestUtils(20640): Calling url: https://api.kommunicate.io/users/v2/chat/plugin/settings?appId=3a2d4cf17baadec3a76c443d618e161b3
I/HttpRequestUtils(20640): Calling url: https://chat.kommunicate.io/rest/ws/register/refresh/token
W/System  (20640): Ignoring header Device-Key because its value was null.
I/System.out(20640): [okhttp]:check permission begin!
I/System.out(20640): [socket]:check permission begin!
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(20640): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(20640): [OkHttp] sendRequest>>
I/System.out(20640): [OkHttp] sendRequest<<
I/HttpRequestUtils(20640): Response : {"status":"error","errorResponse":[{"errorCode":"AL-GE-01","description":"Application key or UserId as request body or device key as header not passed","displayMessage":"Unable to process"}],"generatedAt":1605199951665}
I/System.out(20640): [okhttp]:check permission begin!
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(20640): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(20640): [socket]:check permission begin!
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(20640): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(20640): [OkHttp] sendRequest>>
I/System.out(20640): [OkHttp] sendRequest<<
I/HttpRequestUtils(20640): Response :{"code":"SUCCESS","response":{"userName":"Cheerful Squid","agentId":"mahmoudaraby36@gmail.com","agentName":"Mahmoud Araby","chatWidget":{"popup":true,"position":"right","iconIndex":1,"fileUpload":"awsS3Server","voiceInput":true,"voiceOutput":true,"primaryColor":"#ecca5d","showPoweredBy":true,"sessionTimeout":2592000000,"widgetImageLink":"","notificationTone":"subtle","botMessageDelayInterval":2000},"collectFeedback":true,"customerCreatedAt":"2020-11-11T17:13:02.000Z","chatPopupMessage":[]}}
W/rior.design.ap(20640): Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
W/rior.design.ap(20640): Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, reflection, allowed)
I/RegisterUserClient(20640): Net statustrue
I/RegisterUserClient(20640): Registration json {"chatNotificationMailSent":true,"appVersionCode":112,"applicationId":"3a2d4cf17baadec3a76c443d618e161b3","authenticationTypeId":1,"deviceType":1,"emailVerified":true,"enableEncryption":false,"hideActionMessages":true,"prefContactAPI":2,"roleName":"USER","roleType":3,"skipDeletedGroups":true,"timezone":"Africa/Cairo","userId":"ZO5yZyqoUtkBQVwb3bKGewD8vElc37V1","userIdRegex":"^[a-zA-Z0-9_+#@.?|\u003d;-]+$"}
I/System.out(20640): [okhttp]:check permission begin!
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(20640): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(20640): [OkHttp] sendRequest>>
I/System.out(20640): [OkHttp] sendRequest<<
I/HttpRequestUtils(20640): Response: {"message":"REGISTERED.WITHOUTREGISTRATIONID","userKey":"4334f065-e26e-4a38-a147-34b75e5848fa","deviceKey":"ba6b9105-4288-45ea-adfd-a4801d6b5353","userId":"ZO5yZyqoUtkBQVwb3bKGewD8vElc37V1","displayName":"ZO5yZyqoUtkBQVwb3bKGewD8vElc37V1","lastSyncTime":1605199953450,"currentTimeStamp":1605199953430,"deactivate":false,"brokerUrl":"tcp://socket2.applozic.com:8080","pricingPackage":111,"userEncryptionKey":"d0f45819-d013-46","totalUnreadCount":0,"roleType":3,"notifyState":1,"metadata":{},"newUser":true,"notificationAfter":1605199953437,"authToken":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJaTzV5Wnlxb1V0a0JRVndiM2JLR2V3RDh2RWxjMzdWMSIsInVzZXJLZXkiOiI0MzM0ZjA2NS1lMjZlLTRhMzgtYTE0Ny0zNGI3NWU1ODQ4ZmEiLCJhcHBsaWNhdGlvbklkIjoiM2EyZDRjZjE3YmFhZGVjM2E3NmM0NDNkNjE4ZTE2MWIzIiwiZGV2aWNlS2V5IjoiYmE2YjkxMDUtNDI4OC00NWVhLWFkZmQtYTQ4MDFkNmI1MzUzIiwiY3JlYXRlZEF0VGltZSI6MTYwNTE5OTk1MzQ3NywidmFsaWRVcHRvIjo0MzIwMH0.2olPkEdFduXoGJnGG6Pek25EW6NKk_ugBuTtEkICfiO4VR4dEHBFHm2Ai8Xb-TaANihX6ADb7Epbd14A3hHNbA"}
I/RegisterUserClient(20640): Registration response is: {"message":"REGISTERED.WITHOUTREGISTRATIONID","userKey":"4334f065-e26e-4a38-a147-34b75e5848fa","deviceKey":"ba6b9105-4288-45ea-adfd-a4801d6b5353","userId":"ZO5yZyqoUtkBQVwb3bKGewD8vElc37V1","displayName":"ZO5yZyqoUtkBQVwb3bKGewD8vElc37V1","lastSyncTime":1605199953450,"currentTimeStamp":1605199953430,"deactivate":false,"brokerUrl":"tcp://socket2.applozic.com:8080","pricingPackage":111,"userEncryptionKey":"d0f45819-d013-46","totalUnreadCount":0,"roleType":3,"notifyState":1,"metadata":{},"newUser":true,"notificationAfter":1605199953437,"authToken":"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJaTzV5Wnlxb1V0a0JRVndiM2JLR2V3RDh2RWxjMzdWMSIsInVzZXJLZXkiOiI0MzM0ZjA2NS1lMjZlLTRhMzgtYTE0Ny0zNGI3NWU1ODQ4ZmEiLCJhcHBsaWNhdGlvbklkIjoiM2EyZDRjZjE3YmFhZGVjM2E3NmM0NDNkNjE4ZTE2MWIzIiwiZGV2aWNlS2V5IjoiYmE2YjkxMDUtNDI4OC00NWVhLWFkZmQtYTQ4MDFkNmI1MzUzIiwiY3JlYXRlZEF0VGltZSI6MTYwNTE5OTk1MzQ3NywidmFsaWRVcHRvIjo0MzIwMH0.2olPkEdFduXoGJnGG6Pek25EW6NKk_ugBuTtEkICfiO4VR4dEHBFHm2Ai8Xb-TaANihX6ADb7Epbd14A3hHNbA"}
I/Registration response (20640): is RegistrationResponse{message='REGISTERED.WITHOUTREGISTRATIONID', deviceKey='ba6b9105-4288-45ea-adfd-a4801d6b5353', userKey='4334f065-e26e-4a38-a147-34b75e5848fa', userId='ZO5yZyqoUtkBQVwb3bKGewD8vElc37V1', contactNumber='null', lastSyncTime=1605199953450, currentTimeStamp=1605199953430, displayName='ZO5yZyqoUtkBQVwb3bKGewD8vElc37V1', notificationResponse='null', brokerUrl='tcp://socket2.applozic.com:8080', imageLink='null', statusMessage='null', encryptionKey='null', userEncryptionKey='d0f45819-d013-46', enableEncryption=false, metadata={}, roleType=3, authToken='eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJaTzV5Wnlxb1V0a0JRVndiM2JLR2V3RDh2RWxjMzdWMSIsInVzZXJLZXkiOiI0MzM0ZjA2NS1lMjZlLTRhMzgtYTE0Ny0zNGI3NWU1ODQ4ZmEiLCJhcHBsaWNhdGlvbklkIjoiM2EyZDRjZjE3YmFhZGVjM2E3NmM0NDNkNjE4ZTE2MWIzIiwiZGV2aWNlS2V5IjoiYmE2YjkxMDUtNDI4OC00NWVhLWFkZmQtYTQ4MDFkNmI1MzUzIiwiY3JlYXRlZEF0VGltZSI6MTYwNTE5OTk1MzQ3NywidmFsaWRVcHRvIjo0MzIwMH0.2olPkEdFduXoGJnGG6Pek25EW6NKk_ugBuTtEkICfiO4VR4dEHBFHm2Ai8Xb-TaANihX6ADb7Epbd14A3hHNbA', pricingPackage=111, notificationAfter=1605199953437}
I/NotificationChannels(20640): Created notification channel
I/NotificationChannels(20640): Created silent notification channel
I/ConversationIntent(20640): Syncing messages service started: false
I/ConversationIntent(20640): Syncing messages service started: false
I/ConversationIntent(20640): Muted user list sync started..
I/HttpRequestUtils(20640): Calling url: https://chat.kommunicate.io/rest/ws/user/chat/mute/list
I/System.out(20640): [okhttp]:check permission begin!
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/HttpRequestUtils(20640): Calling url: https://chat.kommunicate.io/rest/ws/message/list?startIndex=0&mainPageSize=60&&deletedGroupIncluded=false
I/System.out(20640): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(20640): [OkHttp] sendRequest>>
I/System.out(20640): [OkHttp] sendRequest<<
I/System.out(20640): [okhttp]:check permission begin!
I/RegisterUserClient(20640): Registration update json {"appVersionCode":112,"applicationId":"3a2d4cf17baadec3a76c443d618e161b3","authenticationTypeId":1,"deviceType":1,"emailVerified":true,"enableEncryption":false,"hideActionMessages":false,"prefContactAPI":2,"registrationId":"eD-uFaUeRSurBXsv_9fu2u:APA91bF1CVYD1Z6MdLv2hmyrd6pXbZ8v5oZwp-dtogcHP9DGq0A6tvdmw11uF679bS2P_xe4tzAMNFYTmDyatVfDP2euniFOwvsR6g4bb8j8vJ9FJMW1HSQGTQneS4Z5i5jcChve_X90","roleName":"USER","roleType":3,"skipDeletedGroups":false,"timezone":"Africa/Cairo","userId":"ZO5yZyqoUtkBQVwb3bKGewD8vElc37V1"}
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(20640): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(20640): [okhttp]:check permission begin!
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(20640): [socket]:check permission begin!
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(20640): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(20640): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(20640): [socket]:check permission begin!
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(20640): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/Timeline(20640): Timeline: Activity_launch_request time:135341255
I/ApplozicMqttService(20640): Connecting to mqtt...
W/ActivityThread(20640): handleWindowVisibility: no activity for token android.os.BinderProxy@b1aa9cf
W/rior.design.ap(20640): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/rior.design.ap(20640): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/HttpRequestUtils(20640): Response :[]
I/UserClientService(20640): Muted users list reponse : []
I/System.out(20640): [socket]:check permission begin!
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(20640): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
E/rior.design.ap(20640): No package ID ff found for ID 0xffffffff.
I/System.out(20640): [OkHttp] sendRequest>>
I/System.out(20640): [OkHttp] sendRequest<<
I/System.out(20640): [OkHttp] sendRequest>>
I/System.out(20640): [OkHttp] sendRequest<<
W/Activity(20640): Slow Operation: Activity com.scope.interior.design.app/com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity onStart took 195ms
V/PhoneWindow(20640): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@9a0e582[]
D/ViewRootImpl[ConversationActivity](20640): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
I/HttpRequestUtils(20640): Calling url: https://chat.kommunicate.io/rest/ws/message/list?startIndex=0&mainPageSize=60&&deletedGroupIncluded=false
V/PhoneWindow(20640): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@ecbe4c9, this = DecorView@9a0e582[ConversationActivity]
I/System.out(20640): [okhttp]:check permission begin!
W/System  (20640): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
W/Looper  (20640): Slow Looper main: Activity com.scope.interior.design.app/com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity is 363ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 4 msg, msg 4 took 359ms (seq=519 late=5ms h=android.app.ActivityThread$H w=159)
I/System.out(20640): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(20640): [OkHttp] sendRequest>>
I/System.out(20640): [OkHttp] sendRequest<<
I/ConnectivityReceiver(20640): android.net.conn.CONNECTIVITY_CHANGE

**Comment by Samir1810** [comment]
Hi, As you have opened the issue via chat, we'll handle and update you in the chat. 
![Flutter-error](https://user-images.githubusercontent.com/60599907/98996976-c4436400-2559-11eb-9882-90b23d67f397.JPG)

**Comment by achinverma** [comment]
Hi, I am getting the same issue, any help for me.

```
Calling url: https://api.kommunicate.io/users/v2/chat/plugin/settings?appId=3fa16425bc95756a95d34b6ec6710c56d
I/HttpRequestUtils(17893): Calling url: https://chat.kommunicate.io/rest/ws/register/refresh/token
W/System  (17893): Ignoring header Device-Key because its value was null.
I/HttpRequestUtils(17893): Response : {"status":"error","errorResponse":[{"errorCode":"AL-GE-01","description":"Application key or UserId as request body or device key as header not passed","displayMessage":"Unable to process"}],"generatedAt":1609411927813}
I/HttpRequestUtils(17893): Response :{"code":"SUCCESS","response":{"userName":"Suave Octopus","agentId":"achin@signitysolutions.in","agentName":"Achin Verma","chatWidget":{"fileUpload":"awsS3Server","notificationTone":"subtle","botMessageDelayInterval":1000},"collectFeedback":true,"customerCreatedAt":"2020-12-30T12:02:59.000Z","chatPopupMessage":[]}}
```
